example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import logout_user #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import show_wishlist_ajax
from wishlist.views import add_item_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat
    path('logout/', logout_user, name='logout'), #sesuaikan dengan nama fungsi yang dibuat
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit/', add_item_ajax, name='add_item')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
import re
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.http import JsonResponse
from django.core import serializers
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Jaycent',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
        'nama': 'Jaycent',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
def add_item_ajax(request):
    response_data = {}
    if request.POST.get('action') == 'post':
        nama = request.POST.get('nama_barang')
        harga = request.POST.get('harga_barang')
        deskripsi = request.POST.get('deskripsi')

        response_data['nama_barang'] = nama
        response_data['harga_barang'] = harga
        response_data['deskripsi'] = deskripsi

        BarangWishlist.objects.create(
            nama_barang = nama,
            harga_barang = harga,
            deskripsi = deskripsi,
        )
        return JsonResponse(response_data)
    

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<title>Login</title>
{% endblock meta %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<div class = "login">

    <h2 style="font-weight: bold; text-align: center; margin-top: 30px;">Login</h2>
    <div class="form" style="padding: 30px">
    <form method="POST" action="">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username:</label>
            <input type="text" name="username" placeholder="Username" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">Password:</label>
            <input type="password" name="password" placeholder="Password" class="form-control">
        </div>
        Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a><br><br>
        <input class="btn login_btn btn-primary" type="submit" value="Login">
        
    </form>
    </div>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<div class = "login">
    
    <h2 style="font-weight: bold; text-align: center; margin-top: 30px;">Formulir Registrasi</h2>  
    <div class="form" style="padding: 30px">
        <form method="POST" >  
            {% csrf_token %}  
            <table class="table table-bordered">  
                {{ form.as_table }}   
            </table>
            <div class="d-grid gap-2 col-6 mx-auto">
                <td><input type="submit" name="submit" value="Daftar" class="btn btn-success"/></td>  
            </div>
        </form>
    </div>
    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block meta %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<title>Wishlist</title>
{% endblock meta %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<nav class="navbar" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <span class="navbar-brand mb-0 h1" style="font-weight: bold;">My Wishlist 📝</span>
        <span class="navbar-text">Halo, <span style="font-weight: bold;">{{nama}}</span>!</span>
        <a class="btn btn-outline-danger" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
    </div>
</nav>

<table class="table table-hover table-bordered">
    <tr>
    <th scope="col" style="text-align: center;">Nama Barang</th>
    <th scope="col" style="text-align: center;">Harga Barang</th>
    <th scope="col" style="text-align: center;">Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th scope="row" style="font-weight: normal; text-align: center;">{{barang.nama_barang}}</th>
        <th style="font-weight: normal; text-align: center;">{{barang.harga_barang}}</th>
        <th style="font-weight: normal; text-align: center;">{{barang.deskripsi}}</th>
    </tr>
{% endfor %}
</table>
<p class="font-weight-light" style="font-size:x-small; text-align: center;">Sesi terakhir login: {{ last_login }}</p>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<title>Wishlist</title>
{% endblock meta %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $.getJSON('/wishlist/json/', function(data) {
            var item = '';
            $.each(data, function(key, value) {
                item += '<tr>';
                item += '<td scope="row" style="font-weight: normal; text-align: center;">' +
                    value.fields.nama_barang + '</td>';
                item += '<td style="font-weight: normal; text-align: center;">' +
                    value.fields.harga_barang + '</td>';
                item += '<td style="font-weight: normal; text-align: center;">' +
                    value.fields.deskripsi + '</td>';
                item += '</tr>';
            });
            $('.table').append(item);
        });
    });

    $(document).on('submit', '#form', function(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '/wishlist/ajax/submit/',
            data:{
                nama_barang:$('#nama_barang').val(),
                harga_barang:$('#harga_barang').val(),
                deskripsi:$('#deskripsi').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action:'post'
            },
            success:function(data){
                var item = '';
                item += '<tr>';
                item += '<td scope="row" style="font-weight: normal; text-align: center;">' +
                    data.nama_barang + '</td>';
                item += '<td style="font-weight: normal; text-align: center;">' +
                    data.harga_barang + '</td>';
                item += '<td style="font-weight: normal; text-align: center;">' +
                    data.deskripsi + '</td>';
                item += '</tr>';
                $('.table').append(item);
                $("#form")[0].reset();
            },
        });
    });
</script>
<nav class="navbar" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <span class="navbar-brand mb-0 h1" style="font-weight: bold;">My Wishlist 📝</span>
        <span class="navbar-text">Halo, <span style="font-weight: bold;">{{nama}}</span>!</span>
        <a class="btn btn-outline-danger" href="{% url 'wishlist:logout' %}" role="button">Logout</a>
    </div>
</nav>

<form id="form" method="POST">
    {% csrf_token %}
    <div class="form-group m-3">
        <label for="nama_barang">Nama Barang</label>
        <input type="text" class="form-control" id="nama_barang" name="harga_barang" placeholder="Nama Barang">
    </div>
    <div class="form-group m-3">
        <label for="harga_barang">Harga Barang</label>
        <input type="text" class="form-control" id="harga_barang" name="harga_barang" placeholder="Harga Barang">
    </div>
    <div class="form-group mx-3 mt-3">
        <label for="deskripsi">Deskripsi</label>
        <input type="text" class="form-control" id="deskripsi" name="deskripsi" placeholder="Deskripsi">
    </div>
    <button type="submit" class="btn btn-primary mx-3 my-2">Submit</button>
</form>

<table class="table table-hover table-bordered">
    <tr>
    <th scope="col" style="text-align: center;">Nama Barang</th>
    <th scope="col" style="text-align: center;">Harga Barang</th>
    <th scope="col" style="text-align: center;">Deskripsi</th>
    </tr>
    
</table>
<p class="font-weight-light" style="font-size:x-small; text-align: center;">Sesi terakhir login: {{ last_login }}</p>

{% endblock content %}